@echo off
echo Starting ThreatLens AI Backend...
cd /d "%~dp0\backend"
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting server...
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
pause
